version: '3.8'

services:
  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  server:
    build: ./server
    volumes:
      - ./server:/app
      - ~/.gradle:/root/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ./gradlew bootRun