version: '3.8'

services:
  client:
    build:
      context: ./client
      target: production
    ports:
      - "80:80"

  server:
    build: ./server
    environment:
      - SPRING_PROFILES_ACTIVE=prod